task_manager/labels/urls.py
from django.urls import path
from task_manager.labels.views import (
    LabelsListView,
    LabelsCreate,
    LabelsUpdate,
    LabelsDelete,
)


app_name = "labels"


urlpatterns = [
    path("", LabelsListView.as_view(), name="list"),
    path("create/", LabelsCreate.as_view(), name="create"),
    path("<int:pk>/update/", LabelsUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", LabelsDelete.as_view(), name="delete"),
]

task_manager/statuses/urls.py
from task_manager.statuses.views import (
    StatusesListView,
    StatusesUpdateView,
    StatusesCreateView,
    StatusesDeleteView,
)
from django.urls import path


app_name = "statuses"


urlpatterns = [
    path("", StatusesListView.as_view(), name="list"),
    path("create/", StatusesCreateView.as_view(), name="create"),
    path("<int:pk>/update/", StatusesUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", StatusesDeleteView.as_view(), name="delete"),
]

task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks.views import (
    TasksCreate,
    TasksDelete,
    TasksListView,
    TasksUpdate,
    TaskClick,
)

app_name = "tasks"

urlpatterns = [
    path("", TasksListView.as_view(), name="list"),
    path("create/", TasksCreate.as_view(), name="create"),
    path("<int:pk>/update/", TasksUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", TasksDelete.as_view(), name="delete"),
    path("<int:pk>/", TaskClick.as_view(), name="click"),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager.views import IndexView, Logout, Login


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("users/", include("task_manager.users.urls")),
    path("statuses/", include("task_manager.statuses.urls")),
    path("tasks/", include("task_manager.tasks.urls")),
    path("labels/", include("task_manager.labels.urls")),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
]

task_manager/users/urls.py
from django.urls import path
from task_manager.users.views import (
    UsersListView,
    UsersCreate,
    UsersUpdate,
    UsersDelete,
)


app_name = "users"


urlpatterns = [
    path("", UsersListView.as_view(), name="list"),
    path("create/", UsersCreate.as_view(), name="create"),
    path("<int:pk>/update/", UsersUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", UsersDelete.as_view(), name="delete"),
]

task_manager/labels/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy

# Create your models here.


class Labels(models.Model):
    name = models.CharField(gettext_lazy("Name"), max_length=255, unique=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):

        return self.name

task_manager/statuses/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy

# Create your models here.


class Statuses(models.Model):
    name = models.CharField(gettext_lazy("Name"), max_length=255, unique=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):

        return self.name

task_manager/tasks/models.py
from django.db import models
from django.utils import timezone
from task_manager.statuses.models import Statuses
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy
from task_manager.labels.models import Labels

# Create your models here.


class Tasks(models.Model):
    name = models.CharField(gettext_lazy("name"), max_length=255, unique=True)
    status = models.ForeignKey(
        Statuses,
        related_name="status",
        blank=False,
        on_delete=models.PROTECT,
        verbose_name=gettext_lazy("Status"),
    )
    created_at = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        related_name="creator",
        verbose_name=gettext_lazy("Creator"),
    )
    executor = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        related_name="executor",
        null=True,
        blank=True,
        verbose_name=gettext_lazy("Executor"),
    )
    description = models.TextField(gettext_lazy("description"), blank=True)
    labels = models.ManyToManyField(
        Labels,
        through="LabelsTasksReal",
        related_name="labels",
        blank=True,
        verbose_name=gettext_lazy("Labels"),
    )

    def __str__(self):

        return self.name


class LabelsTasksReal(models.Model):
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE)
    label = models.ForeignKey(Labels, on_delete=models.CASCADE)

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):

    def __str__(self):
        return self.get_full_name()

task_manager/labels/forms.py
from django.forms import ModelForm
from task_manager.labels.models import Labels


class LabelForm(ModelForm):

    class Meta:
        model = Labels
        fields = ["name"]

task_manager/statuses/forms.py
from django.forms import ModelForm
from task_manager.statuses.models import Statuses


class StatusForm(ModelForm):

    class Meta:
        model = Statuses
        fields = ["name"]

task_manager/tasks/forms.py
from django.forms import ModelForm
from task_manager.tasks.models import Tasks


class TasksForm(ModelForm):

    class Meta:
        model = Tasks
        fields = ["name", "description", "status", "executor", "labels"]

task_manager/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError


class Create(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = get_user_model()
        fields = [
            "first_name",
            "last_name",
            "username",
            "password1",
            "password2",
        ]


class Update(Create):

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if (
            username
            and (self._meta.model.objects
            .filter(username__iexact=username).exists())
            and self.instance.username != username
        ):
            self._update_errors(
                ValidationError(
                    {
                        "username": self.instance.unique_error_message(
                            self._meta.model, ["username"]
                        )
                    }
                )
            )
        else:
            return username

task_manager/labels/views.py
from django.shortcuts import redirect
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from task_manager.labels.models import Labels
from task_manager.labels.forms import LabelForm
from django.urls import reverse_lazy
from task_manager.mixins import AuthRequired
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext
from django.contrib import messages


# Create your views here.


class LabelsListView(AuthRequired, ListView):
    template_name = "labels/list.html"
    model = Labels


class LabelsCreate(AuthRequired, SuccessMessageMixin, CreateView):
    template_name = "labels/create.html"
    model = Labels
    form_class = LabelForm
    success_url = reverse_lazy("labels:list")
    success_message = gettext("Label create")


class LabelsUpdate(AuthRequired, SuccessMessageMixin, UpdateView):
    template_name = "statuses/update.html"
    model = Labels
    form_class = LabelForm
    success_url = reverse_lazy("labels:list")
    success_message = gettext("Label update")


class LabelsDelete(AuthRequired, SuccessMessageMixin, DeleteView):
    template_name = "labels/delete.html"
    model = Labels
    success_url = reverse_lazy("labels:list")
    success_message = gettext("Label delete")

    def post(self, request, *args, **kwargs):
        if self.get_object().labels.all().exists():
            messages.error(self.request, gettext("label to delete unreal"))
            return redirect("labels:list")
        return super().post(request, *args, **kwargs)

task_manager/statuses/views.py
from django.shortcuts import redirect
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from task_manager.statuses.models import Statuses
from task_manager.statuses.forms import StatusForm
from django.urls import reverse_lazy
from task_manager.mixins import AuthRequired
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext
from django.contrib import messages

# Create your views here.


class StatusesListView(AuthRequired, ListView):
    template_name = "statuses/list.html"
    model = Statuses


class StatusesCreateView(AuthRequired, SuccessMessageMixin, CreateView):
    template_name = "statuses/create.html"
    model = Statuses
    form_class = StatusForm
    success_url = reverse_lazy("statuses:list")
    success_message = gettext("Status create")


class StatusesUpdateView(AuthRequired, SuccessMessageMixin, UpdateView):
    template_name = "statuses/update.html"
    model = Statuses
    form_class = StatusForm
    success_url = reverse_lazy("statuses:list")
    success_message = gettext("Status update")


class StatusesDeleteView(AuthRequired, SuccessMessageMixin, DeleteView):
    template_name = "statuses/delete.html"
    model = Statuses
    success_url = reverse_lazy("statuses:list")
    success_message = gettext("Status delete")

    def post(self, request, *args, **kwargs):
        if self.get_object().status.all().exists():
            messages.error(self.request, gettext("status to delete unreal"))
            return redirect("statuses:list")
        return super().post(request, *args, **kwargs)

task_manager/tasks/views.py
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
)
from task_manager.tasks.forms import TasksForm
from task_manager.mixins import AuthRequired
from django.urls import reverse_lazy
from django.utils.translation import gettext
from django.contrib.messages.views import SuccessMessageMixin
from task_manager.tasks.models import Tasks
from task_manager.tasks.mixins import CheckUser, NoPermissionHandleMixin
from task_manager.tasks.filter import TaskFilter
from django_filters.views import FilterView


class TasksListView(AuthRequired, FilterView):
    success_url = reverse_lazy("tasks:list")
    model = Tasks
    template_name = "tasks/list.html"
    filterset_class = TaskFilter


class TasksCreate(AuthRequired, SuccessMessageMixin, CreateView):
    model = Tasks
    form_class = TasksForm
    template_name = "tasks/create.html"
    success_url = reverse_lazy("tasks:list")
    success_message = gettext("Task create successfull")

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class TasksUpdate(AuthRequired, SuccessMessageMixin, UpdateView):
    model = Tasks
    form_class = TasksForm
    template_name = "tasks/update.html"
    success_url = reverse_lazy("tasks:list")
    success_message = gettext("Task update successfull")


class TasksDelete(
    AuthRequired, NoPermissionHandleMixin, CheckUser,
    SuccessMessageMixin, DeleteView
):
    model = Tasks
    template_name = "tasks/delete.html"
    success_url = reverse_lazy("tasks:list")
    success_message = gettext("Task delete successfull")


class TaskClick(AuthRequired, NoPermissionHandleMixin, DetailView):
    model = Tasks
    template_name = "tasks/click.html"

task_manager/users/views.py
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth import get_user_model
from task_manager.users.forms import Create, Update
from task_manager.mixins import AuthRequired
from django.urls import reverse_lazy
from django.utils.translation import gettext
from django.contrib.messages.views import SuccessMessageMixin
from task_manager.users.mixins import CheckUser, NoPermissionHandleMixin

# Create your views here.


class UsersListView(ListView):
    template_name = "users/list.html"
    model = get_user_model()


class UsersCreate(SuccessMessageMixin, CreateView):
    model = get_user_model()
    template_name = "users/create.html"
    form_class = Create
    success_url = reverse_lazy("login")
    success_message = gettext("User register successfull")


class UsersUpdate(
    AuthRequired, NoPermissionHandleMixin,
    CheckUser, SuccessMessageMixin, UpdateView
):
    model = get_user_model()
    form_class = Update
    template_name = "users/update.html"
    success_url = "/users/"
    success_message = gettext("User update successfull")


class UsersDelete(
    AuthRequired, NoPermissionHandleMixin,
    CheckUser, SuccessMessageMixin, DeleteView
):
    model = get_user_model()
    template_name = "users/delete.html"
    success_url = "/users/"
    success_message = gettext("User delete successfull")

task_manager/views.py
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.utils.translation import gettext
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.messages import info


class IndexView(TemplateView):
    template_name = "index.html"


class Login(SuccessMessageMixin, LoginView):
    template_name = "login.html"
    success_message = gettext("You are log in")


class Logout(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        res = super().dispatch(request, *args, **kwargs)
        info(request, gettext("You are log out"))
        return res

task_manager/templates/base.html
{% load i18n %}
{% load django_bootstrap5 %}
{% get_current_language as LANGUAGE_CODE %}


<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% translate 'hexlet task manager' %}</title>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" rel="stylesheet">
    <script crossorigin="anonymous" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-light ms-3">
      <a class="navbar-brand" href="/">{% translate 'Task Manager' %}</a>
      <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:list' %}">{% translate 'Users' %}</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          
          
          {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <input type="submit" class="btn nav-link" value="{% translate 'Logout' %}">
            </form>

          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">{% translate 'Login' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:create' %}">{% translate 'Registration' %}</a>
            </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'statuses:list' %}">{% translate 'Statuses' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'labels:list' %}">{% translate 'Labels' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:list' %}">{% translate 'Tasks' %}</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% bootstrap_messages %}

    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
      <div class="container my-5 pt-4 border-top">
        <a target="_blank" href="https://ru.hexlet.io">{% translate 'Hexlet' %}</a>
      </div>
    </footer>
  </body>
</html>

task_manager/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4">
        {% translate "Welcome to Hexlet!" %}
    </h1>
    
    <h1 class="my-4"></h1>
    <div class="card">
        <div class="card-body p-5 bg-light">
            <div class="display-4">{% translate "Hello from Hexlet!" %}</div>
            <p class="lead">{% translate "Practical programming courses" %}</p>
            <hr>
            <a class="btn btn-primary btn-lg" href="https://ru.hexlet.io">{% translate "Learn more" %}</a>
        </div>
    </div>
</div>
{% endblock %}

task_manager/templates/login.html
{% extends 'base.html' %}
{% load i18n %}
{% load django_bootstrap5 %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="{% translate 'Log in' %}">
</form>
{% endblock %}

task_manager/templates/logout.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}


<form method="post">
    {% csrf_token %}
    <input type="submit" value="{% translate 'Confirm Logout' %}">
</form>
{% endblock %}